12-Mar-24 11:22:00 INFO [server.py] Started server process [1710771]
12-Mar-24 11:22:00 INFO [on.py] Waiting for application startup.
12-Mar-24 11:22:00 INFO [on.py] Application startup complete.
12-Mar-24 11:23:33 INFO [server.py] Shutting down
12-Mar-24 11:23:33 INFO [on.py] Waiting for application shutdown.
12-Mar-24 11:23:33 INFO [on.py] Application shutdown complete.
12-Mar-24 11:23:33 INFO [server.py] Finished server process [1710771]
12-Mar-24 11:24:28 INFO [server.py] Started server process [1711414]
12-Mar-24 11:24:28 INFO [on.py] Waiting for application startup.
12-Mar-24 11:24:28 INFO [on.py] Application startup complete.
12-Mar-24 11:28:27 INFO [server.py] Shutting down
12-Mar-24 11:28:27 INFO [on.py] Waiting for application shutdown.
12-Mar-24 11:28:27 INFO [on.py] Application shutdown complete.
12-Mar-24 11:28:27 INFO [server.py] Finished server process [1711414]
12-Mar-24 11:29:20 INFO [server.py] Started server process [1712651]
12-Mar-24 11:29:20 INFO [on.py] Waiting for application startup.
12-Mar-24 11:29:20 INFO [on.py] Application startup complete.
12-Mar-24 11:29:22 INFO [server.py] Shutting down
12-Mar-24 11:29:22 INFO [on.py] Waiting for application shutdown.
12-Mar-24 11:29:22 INFO [on.py] Application shutdown complete.
12-Mar-24 11:29:22 INFO [server.py] Finished server process [1712651]
12-Mar-24 11:30:23 INFO [server.py] Started server process [1712862]
12-Mar-24 11:30:23 INFO [on.py] Waiting for application startup.
12-Mar-24 11:30:23 INFO [on.py] Application startup complete.
12-Mar-24 11:31:04 INFO [config.py] Will watch for changes in these directories: ['/opt/siap/analytics']
12-Mar-24 11:31:04 ERROR [config.py] [Errno 98] Address already in use
12-Mar-24 11:32:36 INFO [config.py] Will watch for changes in these directories: ['/opt/siap/analytics']
12-Mar-24 11:32:36 INFO [config.py] Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
12-Mar-24 11:32:36 INFO [basereload.py] Started reloader process [1713844] using StatReload
12-Mar-24 11:33:30 INFO [server.py] Started server process [1714174]
12-Mar-24 11:33:30 INFO [on.py] Waiting for application startup.
12-Mar-24 11:33:30 INFO [on.py] Application startup complete.
12-Mar-24 11:33:33 INFO [h11_impl.py] 192.168.150.14:58570 - "GET /docs HTTP/1.1" 200
12-Mar-24 11:33:33 INFO [h11_impl.py] 192.168.150.14:58570 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 11:33:43 INFO [h11_impl.py] 192.168.150.14:58573 - "POST /token HTTP/1.1" 401
12-Mar-24 11:33:50 INFO [authentication.py] login_for_access_token
12-Mar-24 11:33:50 INFO [authbearer.py] authenticating user
12-Mar-24 11:33:50 INFO [authbearer.py] user found
12-Mar-24 11:33:50 INFO [authbearer.py] Verifying plain password:
12-Mar-24 11:33:50 INFO [authbearer.py] Verifying hashed password:
12-Mar-24 11:33:50 INFO [authbearer.py] User authenticated successfully
12-Mar-24 11:33:50 INFO [authbearer.py] Creating access token for data
12-Mar-24 11:33:50 INFO [h11_impl.py] 192.168.150.14:58578 - "POST /token HTTP/1.1" 200
12-Mar-24 11:35:07 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 11:35:07 INFO [server.py] Shutting down
12-Mar-24 11:35:07 INFO [on.py] Waiting for application shutdown.
12-Mar-24 11:35:07 INFO [on.py] Application shutdown complete.
12-Mar-24 11:35:07 INFO [server.py] Finished server process [1714174]
12-Mar-24 11:35:16 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 11:36:08 INFO [server.py] Started server process [1714734]
12-Mar-24 11:36:08 INFO [on.py] Waiting for application startup.
12-Mar-24 11:36:08 INFO [on.py] Application startup complete.
12-Mar-24 11:36:08 INFO [h11_impl.py] 192.168.150.14:58604 - "GET /docs HTTP/1.1" 200
12-Mar-24 11:36:08 INFO [h11_impl.py] 192.168.150.14:58604 - "GET /docs HTTP/1.1" 200
12-Mar-24 11:36:08 INFO [h11_impl.py] 192.168.150.14:58604 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 11:36:08 INFO [h11_impl.py] 192.168.150.14:58604 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 11:38:12 WARNING [basereload.py] StatReload detected changes in 'swm/router/swm_visualization.py'. Reloading...
12-Mar-24 11:39:15 WARNING [basereload.py] StatReload detected changes in 'swm/router/swm_visualization.py'. Reloading...
12-Mar-24 11:39:57 WARNING [basereload.py] StatReload detected changes in 'swm/router/swm_visualization.py'. Reloading...
12-Mar-24 11:40:48 INFO [server.py] Started server process [1715942]
12-Mar-24 11:40:48 INFO [on.py] Waiting for application startup.
12-Mar-24 11:40:48 INFO [on.py] Application startup complete.
12-Mar-24 11:40:48 INFO [h11_impl.py] 192.168.150.14:58677 - "GET /docs HTTP/1.1" 200
12-Mar-24 11:40:48 INFO [h11_impl.py] 192.168.150.14:58677 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 11:49:09 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 12:14:59 INFO [basereload.py] Stopping reloader process [1713844]
12-Mar-24 12:15:48 INFO [config.py] Will watch for changes in these directories: ['/opt/siap/analytics']
12-Mar-24 12:15:48 INFO [config.py] Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
12-Mar-24 12:15:48 INFO [basereload.py] Started reloader process [1721763] using StatReload
12-Mar-24 12:16:40 INFO [server.py] Started server process [1721939]
12-Mar-24 12:16:40 INFO [on.py] Waiting for application startup.
12-Mar-24 12:16:40 INFO [on.py] Application startup complete.
12-Mar-24 12:16:44 INFO [h11_impl.py] 192.168.150.14:59249 - "GET /docs HTTP/1.1" 200
12-Mar-24 12:16:44 INFO [h11_impl.py] 192.168.150.14:59249 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 12:34:52 WARNING [basereload.py] StatReload detected changes in 'v1/auth/endpoints.py'. Reloading...
12-Mar-24 12:35:47 INFO [server.py] Started server process [1725087]
12-Mar-24 12:35:47 INFO [on.py] Waiting for application startup.
12-Mar-24 12:35:47 INFO [on.py] Application startup complete.
12-Mar-24 12:35:51 INFO [h11_impl.py] 192.168.150.14:59489 - "GET /docs HTTP/1.1" 200
12-Mar-24 12:35:51 INFO [h11_impl.py] 192.168.150.14:59489 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 13:33:06 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 13:33:27 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 13:34:51 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 13:35:42 INFO [server.py] Started server process [1747796]
12-Mar-24 13:35:42 INFO [on.py] Waiting for application startup.
12-Mar-24 13:35:42 INFO [on.py] Application startup complete.
12-Mar-24 13:35:43 INFO [h11_impl.py] 192.168.150.14:60166 - "GET /docs HTTP/1.1" 200
12-Mar-24 13:35:43 INFO [h11_impl.py] 192.168.150.14:60166 - "GET /docs HTTP/1.1" 200
12-Mar-24 13:35:43 INFO [h11_impl.py] 192.168.150.14:60166 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 13:35:43 INFO [h11_impl.py] 192.168.150.14:60166 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 13:39:19 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 13:40:09 INFO [server.py] Started server process [1749874]
12-Mar-24 13:40:09 INFO [on.py] Waiting for application startup.
12-Mar-24 13:40:09 INFO [on.py] Application startup complete.
12-Mar-24 13:40:09 INFO [h11_impl.py] 192.168.150.14:60225 - "GET /docs HTTP/1.1" 200
12-Mar-24 13:40:10 INFO [h11_impl.py] 192.168.150.14:60225 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 13:41:29 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 13:41:29 INFO [server.py] Shutting down
12-Mar-24 13:41:29 INFO [on.py] Waiting for application shutdown.
12-Mar-24 13:41:29 INFO [on.py] Application shutdown complete.
12-Mar-24 13:41:29 INFO [server.py] Finished server process [1749874]
12-Mar-24 13:42:20 INFO [server.py] Started server process [1750780]
12-Mar-24 13:42:20 INFO [on.py] Waiting for application startup.
12-Mar-24 13:42:20 INFO [on.py] Application startup complete.
12-Mar-24 13:42:20 INFO [h11_impl.py] 192.168.150.14:60254 - "GET /docs HTTP/1.1" 200
12-Mar-24 13:42:20 INFO [h11_impl.py] 192.168.150.14:60254 - "GET /docs HTTP/1.1" 200
12-Mar-24 13:42:20 INFO [h11_impl.py] 192.168.150.14:60254 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 13:42:21 INFO [h11_impl.py] 192.168.150.14:60254 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 13:47:30 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 13:48:45 INFO [server.py] Started server process [1753496]
12-Mar-24 13:48:45 INFO [on.py] Waiting for application startup.
12-Mar-24 13:48:45 INFO [on.py] Application startup complete.
12-Mar-24 13:48:45 INFO [h11_impl.py] 192.168.150.14:60334 - "GET /docs HTTP/1.1" 200
12-Mar-24 13:48:45 INFO [h11_impl.py] 192.168.150.14:60334 - "GET /docs HTTP/1.1" 200
12-Mar-24 13:48:46 INFO [h11_impl.py] 192.168.150.14:60334 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 13:48:46 INFO [h11_impl.py] 192.168.150.14:60334 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 13:51:40 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 13:52:34 INFO [server.py] Started server process [1755209]
12-Mar-24 13:52:34 INFO [on.py] Waiting for application startup.
12-Mar-24 13:52:34 INFO [on.py] Application startup complete.
12-Mar-24 13:52:34 INFO [h11_impl.py] 192.168.150.14:60393 - "GET /docs HTTP/1.1" 200
12-Mar-24 13:52:34 INFO [h11_impl.py] 192.168.150.14:60393 - "GET /docs HTTP/1.1" 200
12-Mar-24 13:52:35 INFO [h11_impl.py] 192.168.150.14:60393 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 13:52:35 INFO [h11_impl.py] 192.168.150.14:60393 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 13:54:22 INFO [basereload.py] Stopping reloader process [1721763]
12-Mar-24 13:55:52 INFO [config.py] Will watch for changes in these directories: ['/opt/siap/analytics']
12-Mar-24 13:55:52 INFO [config.py] Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
12-Mar-24 13:55:52 INFO [basereload.py] Started reloader process [1757064] using StatReload
12-Mar-24 13:56:41 INFO [server.py] Started server process [1757404]
12-Mar-24 13:56:41 INFO [on.py] Waiting for application startup.
12-Mar-24 13:56:41 INFO [on.py] Application startup complete.
12-Mar-24 13:56:46 INFO [h11_impl.py] 192.168.150.14:60461 - "GET /docs HTTP/1.1" 200
12-Mar-24 13:56:47 INFO [h11_impl.py] 192.168.150.14:60461 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:02:22 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:03:06 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:03:56 INFO [server.py] Started server process [1760541]
12-Mar-24 14:03:56 INFO [on.py] Waiting for application startup.
12-Mar-24 14:03:56 INFO [on.py] Application startup complete.
12-Mar-24 14:03:57 INFO [h11_impl.py] 192.168.150.14:60553 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:03:57 INFO [h11_impl.py] 192.168.150.14:60554 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:03:57 INFO [h11_impl.py] 192.168.150.14:60554 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:03:57 INFO [h11_impl.py] 192.168.150.14:60553 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:04:25 INFO [h11_impl.py] 192.168.150.14:60561 - "POST /token HTTP/1.1" 401
12-Mar-24 14:08:59 WARNING [basereload.py] StatReload detected changes in 'v1/swm/endpoints.py'. Reloading...
12-Mar-24 14:09:49 WARNING [basereload.py] StatReload detected changes in 'v1/swm/endpoints.py'. Reloading...
12-Mar-24 14:10:41 INFO [server.py] Started server process [1763527]
12-Mar-24 14:10:41 INFO [on.py] Waiting for application startup.
12-Mar-24 14:10:41 INFO [on.py] Application startup complete.
12-Mar-24 14:10:44 INFO [h11_impl.py] 192.168.150.14:60640 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:10:44 INFO [h11_impl.py] 192.168.150.14:60640 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:11:33 WARNING [basereload.py] StatReload detected changes in 'v1/swm/endpoints.py'. Reloading...
12-Mar-24 14:11:33 INFO [server.py] Shutting down
12-Mar-24 14:11:33 INFO [server.py] Waiting for connections to close. (CTRL+C to force quit)
12-Mar-24 14:11:36 INFO [on.py] Waiting for application shutdown.
12-Mar-24 14:11:36 INFO [on.py] Application shutdown complete.
12-Mar-24 14:11:36 INFO [server.py] Finished server process [1763527]
12-Mar-24 14:12:29 INFO [server.py] Started server process [1764334]
12-Mar-24 14:12:29 INFO [on.py] Waiting for application startup.
12-Mar-24 14:12:29 INFO [on.py] Application startup complete.
12-Mar-24 14:12:29 INFO [h11_impl.py] 192.168.150.14:60668 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:12:29 INFO [h11_impl.py] 192.168.150.14:60669 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:12:30 INFO [h11_impl.py] 192.168.150.14:60669 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:12:30 INFO [h11_impl.py] 192.168.150.14:60668 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:19:30 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:20:20 INFO [server.py] Started server process [1767695]
12-Mar-24 14:20:20 INFO [on.py] Waiting for application startup.
12-Mar-24 14:20:20 INFO [on.py] Application startup complete.
12-Mar-24 14:20:21 INFO [h11_impl.py] 192.168.150.14:60763 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:20:21 INFO [h11_impl.py] 192.168.150.14:60763 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:20:21 INFO [h11_impl.py] 192.168.150.14:60763 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:20:22 INFO [h11_impl.py] 192.168.150.14:60763 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:22:49 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 14:23:42 INFO [server.py] Started server process [1769165]
12-Mar-24 14:23:42 INFO [on.py] Waiting for application startup.
12-Mar-24 14:23:42 INFO [on.py] Application startup complete.
12-Mar-24 14:23:42 INFO [h11_impl.py] 192.168.150.14:60812 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:23:42 INFO [h11_impl.py] 192.168.150.14:60812 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:23:43 INFO [h11_impl.py] 192.168.150.14:60812 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:23:43 INFO [h11_impl.py] 192.168.150.14:60812 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:23:43 INFO [h11_impl.py] 192.168.150.14:60812 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:25:47 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:26:41 INFO [server.py] Started server process [1770464]
12-Mar-24 14:26:41 INFO [on.py] Waiting for application startup.
12-Mar-24 14:26:41 INFO [on.py] Application startup complete.
12-Mar-24 14:30:21 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:30:21 INFO [server.py] Shutting down
12-Mar-24 14:30:21 INFO [on.py] Waiting for application shutdown.
12-Mar-24 14:30:21 INFO [on.py] Application shutdown complete.
12-Mar-24 14:30:21 INFO [server.py] Finished server process [1770464]
12-Mar-24 14:30:47 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:31:38 INFO [server.py] Started server process [1772589]
12-Mar-24 14:31:38 INFO [on.py] Waiting for application startup.
12-Mar-24 14:31:38 INFO [on.py] Application startup complete.
12-Mar-24 14:31:44 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:31:44 INFO [server.py] Shutting down
12-Mar-24 14:31:44 INFO [on.py] Waiting for application shutdown.
12-Mar-24 14:31:44 INFO [on.py] Application shutdown complete.
12-Mar-24 14:31:44 INFO [server.py] Finished server process [1772589]
12-Mar-24 14:38:13 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:43:55 WARNING [basereload.py] StatReload detected changes in 'v1/auth/endpoints.py'. Reloading...
12-Mar-24 14:44:00 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:44:39 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 14:45:51 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:46:53 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 14:49:01 WARNING [basereload.py] StatReload detected changes in 'swm/router/swm_visualization.py'. Reloading...
12-Mar-24 14:53:23 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:54:34 WARNING [basereload.py] StatReload detected changes in 'v1/swm/endpoints.py'. Reloading...
12-Mar-24 14:55:24 INFO [server.py] Started server process [1783132]
12-Mar-24 14:55:24 INFO [on.py] Waiting for application startup.
12-Mar-24 14:55:24 INFO [on.py] Application startup complete.
12-Mar-24 14:55:24 INFO [h11_impl.py] 192.168.150.14:61243 - "GET /docs HTTP/1.1" 200
12-Mar-24 14:55:25 INFO [h11_impl.py] 192.168.150.14:61243 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 14:55:43 INFO [h11_impl.py] 192.168.150.14:61248 - "POST /token HTTP/1.1" 400
12-Mar-24 14:56:48 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 14:56:48 INFO [server.py] Shutting down
12-Mar-24 14:56:48 INFO [on.py] Waiting for application shutdown.
12-Mar-24 14:56:48 INFO [on.py] Application shutdown complete.
12-Mar-24 14:56:48 INFO [server.py] Finished server process [1783132]
12-Mar-24 14:57:40 INFO [server.py] Started server process [1784091]
12-Mar-24 14:57:40 INFO [on.py] Waiting for application startup.
12-Mar-24 14:57:40 INFO [on.py] Application startup complete.
12-Mar-24 14:59:57 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 14:59:57 INFO [server.py] Shutting down
12-Mar-24 14:59:57 INFO [on.py] Waiting for application shutdown.
12-Mar-24 14:59:57 INFO [on.py] Application shutdown complete.
12-Mar-24 14:59:57 INFO [server.py] Finished server process [1784091]
12-Mar-24 15:00:48 INFO [server.py] Started server process [1785412]
12-Mar-24 15:00:48 INFO [on.py] Waiting for application startup.
12-Mar-24 15:00:48 INFO [on.py] Application startup complete.
12-Mar-24 15:00:49 INFO [h11_impl.py] 192.168.150.14:61325 - "GET /docs HTTP/1.1" 200
12-Mar-24 15:00:49 INFO [h11_impl.py] 192.168.150.14:61325 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 15:01:06 INFO [h11_impl.py] 192.168.150.14:61333 - "POST /token HTTP/1.1" 400
12-Mar-24 15:03:03 WARNING [basereload.py] StatReload detected changes in 'v1/auth/endpoints.py'. Reloading...
12-Mar-24 15:03:03 INFO [server.py] Shutting down
12-Mar-24 15:03:03 INFO [on.py] Waiting for application shutdown.
12-Mar-24 15:03:03 INFO [on.py] Application shutdown complete.
12-Mar-24 15:03:03 INFO [server.py] Finished server process [1785412]
12-Mar-24 15:04:06 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 15:05:14 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 15:05:59 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 15:06:49 INFO [server.py] Started server process [1788656]
12-Mar-24 15:06:49 INFO [on.py] Waiting for application startup.
12-Mar-24 15:06:49 INFO [on.py] Application startup complete.
12-Mar-24 15:06:55 INFO [h11_impl.py] 192.168.150.14:61422 - "GET /docs HTTP/1.1" 200
12-Mar-24 15:06:55 INFO [h11_impl.py] 192.168.150.14:61422 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 15:07:13 INFO [h11_impl.py] 192.168.150.14:61427 - "POST /token HTTP/1.1" 500
12-Mar-24 15:07:13 ERROR [h11_impl.py] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/siap/analytics/auth/authentication.py", line 40, in login_for_access_token
    logger=setup_logger(config.LOG_FILE_PATH['auth_logs_path'],config.LOG_FILE_PATH['auth_logs_name'])
NameError: name 'setup_logger' is not defined
12-Mar-24 15:08:05 INFO [h11_impl.py] 192.168.150.14:61438 - "POST /token HTTP/1.1" 500
12-Mar-24 15:08:05 ERROR [h11_impl.py] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/siap/analytics/auth/authentication.py", line 40, in login_for_access_token
    logger=setup_logger(config.LOG_FILE_PATH['auth_logs_path'],config.LOG_FILE_PATH['auth_logs_name'])
NameError: name 'setup_logger' is not defined
12-Mar-24 15:11:54 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 15:11:54 INFO [server.py] Shutting down
12-Mar-24 15:11:54 INFO [server.py] Waiting for connections to close. (CTRL+C to force quit)
12-Mar-24 15:11:58 INFO [on.py] Waiting for application shutdown.
12-Mar-24 15:11:58 INFO [on.py] Application shutdown complete.
12-Mar-24 15:11:58 INFO [server.py] Finished server process [1788656]
12-Mar-24 15:12:48 INFO [server.py] Started server process [1791194]
12-Mar-24 15:12:48 INFO [on.py] Waiting for application startup.
12-Mar-24 15:12:48 INFO [on.py] Application startup complete.
12-Mar-24 15:12:48 INFO [h11_impl.py] 192.168.150.14:61508 - "GET /docs HTTP/1.1" 200
12-Mar-24 15:12:48 INFO [h11_impl.py] 192.168.150.14:61508 - "GET /docs HTTP/1.1" 200
12-Mar-24 15:12:48 INFO [h11_impl.py] 192.168.150.14:61508 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 15:12:48 INFO [h11_impl.py] 192.168.150.14:61508 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 15:12:54 INFO [h11_impl.py] 192.168.150.14:61511 - "POST /token HTTP/1.1" 500
12-Mar-24 15:12:54 ERROR [h11_impl.py] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/siap/analytics/auth/authentication.py", line 40, in login_for_access_token
    logger=setup_logger(config.LOG_FILE_PATH['auth_logs_path'],config.LOG_FILE_PATH['auth_logs_name'])
NameError: name 'setup_logger' is not defined
12-Mar-24 15:13:14 INFO [h11_impl.py] 192.168.150.14:61517 - "POST /token HTTP/1.1" 500
12-Mar-24 15:13:14 ERROR [h11_impl.py] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/opt/siap/analytics/analytics_env/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/siap/analytics/auth/authentication.py", line 40, in login_for_access_token
    logger=setup_logger(config.LOG_FILE_PATH['auth_logs_path'],config.LOG_FILE_PATH['auth_logs_name'])
NameError: name 'setup_logger' is not defined
12-Mar-24 15:16:33 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 15:16:33 INFO [server.py] Shutting down
12-Mar-24 15:16:33 INFO [server.py] Waiting for connections to close. (CTRL+C to force quit)
12-Mar-24 15:21:23 INFO [config.py] Will watch for changes in these directories: ['/opt/siap/analytics']
12-Mar-24 15:21:23 ERROR [config.py] [Errno 98] Address already in use
12-Mar-24 15:33:30 INFO [config.py] Will watch for changes in these directories: ['/opt/siap/analytics']
12-Mar-24 15:33:30 ERROR [config.py] [Errno 98] Address already in use
12-Mar-24 15:35:32 INFO [config.py] Will watch for changes in these directories: ['/opt/siap/analytics']
12-Mar-24 15:35:32 INFO [config.py] Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
12-Mar-24 15:35:32 INFO [basereload.py] Started reloader process [1804004] using StatReload
12-Mar-24 15:36:37 INFO [server.py] Started server process [1804464]
12-Mar-24 15:36:37 INFO [on.py] Waiting for application startup.
12-Mar-24 15:36:37 INFO [on.py] Application startup complete.
12-Mar-24 15:41:08 INFO [h11_impl.py] 192.168.150.14:62274 - "GET /docs HTTP/1.1" 200
12-Mar-24 15:41:09 INFO [h11_impl.py] 192.168.150.14:62274 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 16:08:17 INFO [h11_impl.py] 192.168.150.14:62591 - "GET /docs HTTP/1.1" 200
12-Mar-24 16:08:18 INFO [h11_impl.py] 192.168.150.14:62591 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 16:09:20 WARNING [basereload.py] StatReload detected changes in 'swm/router/swm_visualization.py'. Reloading...
12-Mar-24 16:10:33 WARNING [basereload.py] StatReload detected changes in 'swm/router/swm_visualization.py'. Reloading...
12-Mar-24 16:11:06 WARNING [basereload.py] StatReload detected changes in 'v1/auth/endpoints.py'. Reloading...
12-Mar-24 16:15:56 WARNING [basereload.py] StatReload detected changes in 'v1/auth/endpoints.py'. Reloading...
12-Mar-24 16:16:15 WARNING [basereload.py] StatReload detected changes in 'swm/router/swm_visualization.py'. Reloading...
12-Mar-24 16:17:52 INFO [server.py] Started server process [1822628]
12-Mar-24 16:17:52 INFO [on.py] Waiting for application startup.
12-Mar-24 16:17:52 INFO [on.py] Application startup complete.
12-Mar-24 16:17:52 INFO [h11_impl.py] 192.168.150.14:62786 - "GET /docs HTTP/1.1" 200
12-Mar-24 16:17:52 INFO [h11_impl.py] 192.168.150.14:62786 - "GET /docs HTTP/1.1" 200
12-Mar-24 16:17:52 INFO [h11_impl.py] 192.168.150.14:62786 - "GET /docs HTTP/1.1" 200
12-Mar-24 16:17:53 INFO [h11_impl.py] 192.168.150.14:62786 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 16:17:54 INFO [h11_impl.py] 192.168.150.14:62786 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 16:17:54 INFO [h11_impl.py] 192.168.150.14:62786 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 16:27:43 WARNING [basereload.py] StatReload detected changes in 'auth/authentication.py'. Reloading...
12-Mar-24 16:29:19 INFO [server.py] Started server process [1827927]
12-Mar-24 16:29:19 INFO [on.py] Waiting for application startup.
12-Mar-24 16:29:19 INFO [on.py] Application startup complete.
12-Mar-24 16:29:21 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 16:29:21 INFO [server.py] Shutting down
12-Mar-24 16:29:21 INFO [on.py] Waiting for application shutdown.
12-Mar-24 16:29:21 INFO [on.py] Application shutdown complete.
12-Mar-24 16:29:21 INFO [server.py] Finished server process [1827927]
12-Mar-24 16:30:58 INFO [server.py] Started server process [1828673]
12-Mar-24 16:30:58 INFO [on.py] Waiting for application startup.
12-Mar-24 16:30:58 INFO [on.py] Application startup complete.
12-Mar-24 16:30:58 INFO [h11_impl.py] 192.168.150.14:62979 - "GET /docs HTTP/1.1" 200
12-Mar-24 16:30:58 INFO [h11_impl.py] 192.168.150.14:62980 - "GET /docs HTTP/1.1" 200
12-Mar-24 16:30:59 INFO [h11_impl.py] 192.168.150.14:62980 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 16:30:59 INFO [h11_impl.py] 192.168.150.14:62979 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 16:43:18 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 16:44:52 INFO [server.py] Started server process [1834740]
12-Mar-24 16:44:52 INFO [on.py] Waiting for application startup.
12-Mar-24 16:44:52 INFO [on.py] Application startup complete.
12-Mar-24 16:49:12 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 16:49:57 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 16:50:38 INFO [basereload.py] Stopping reloader process [1804004]
12-Mar-24 16:51:59 INFO [config.py] Will watch for changes in these directories: ['/opt/siap/analytics']
12-Mar-24 16:51:59 INFO [config.py] Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
12-Mar-24 16:51:59 INFO [basereload.py] Started reloader process [1838280] using StatReload
12-Mar-24 16:53:07 INFO [server.py] Started server process [1838836]
12-Mar-24 16:53:07 INFO [on.py] Waiting for application startup.
12-Mar-24 16:53:07 INFO [on.py] Application startup complete.
12-Mar-24 16:53:39 INFO [h11_impl.py] 192.168.150.14:63272 - "GET /docs HTTP/1.1" 200
12-Mar-24 16:53:39 INFO [h11_impl.py] 192.168.150.14:63272 - "GET /openapi.json HTTP/1.1" 200
12-Mar-24 16:56:49 WARNING [basereload.py] StatReload detected changes in 'auth/authbearer.py'. Reloading...
12-Mar-24 16:58:26 INFO [server.py] Started server process [1841055]
12-Mar-24 16:58:26 INFO [on.py] Waiting for application startup.
12-Mar-24 16:58:26 INFO [on.py] Application startup complete.
